#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright 2026 Google LLC
#
# Test copy offloading within a single block device.

. tests/block/rc
. common/null_blk

DESCRIPTION="copy offloading within a single block device"
QUICK=1

requires() {
	_have_fio
	_have_driver null_blk
}

# Compare the contents of block device $1, starting from byte offset $3, with
# the contents of block device $2, starting from byte offset $4. Compare $5
# bytes in total.
cmp_range() {
	if cmp -s -n "$5" "$1" "$2" "$3" "$4"; then
		echo "$*: content identical" >>"$FULL"
		return
	fi
	echo "$*: content differs" >>"$FULL"
	return 1
}

run_test() {
	local mcb

	# The three mcb (max_copy_bytes) values have been chosen as follows:
	# * The first value (65536) is larger than the number of bytes copied
	#   (3 * 4096).
	# * The second value (4096) is smaller than the number of bytes copied.
	# * The third value (0) triggers copying without offloading.
	for mcb in 65536 4096 0; do
		_init_null_blk nr_devices=0
		echo "max_copy_bytes=$mcb ..."
		local nullb_params=(
			blocking=1
			hw_queue_depth=64
			irqmode=0
			max_copy_bytes="$mcb"
			memory_backed=1
			size=1                     # MiB
			submit_queues=1
			power=1
		)
		_configure_null_blk nullb0 "${nullb_params[@]}"
		local bdev=/dev/nullb0
		local src_off=$((1 * 4096))
		local dst_off=$((5 * 4096))
		local count=$((3 * 4096))
		dd if=/dev/urandom of=$bdev bs=64K count=1 >&/dev/null
		if cmp_range "$bdev" "$bdev" $src_off $dst_off $count; then
			echo "Unexpected: source and destination ranges are identical"
			return 1
		fi
		src/copy_file_range $bdev $bdev $src_off $dst_off $count \
				    >>"$FULL" 2>&1
		cmp_range $bdev $bdev $src_off $dst_off $count
		_exit_null_blk
	done
}

test() {
	echo "Running ${TEST_NAME}"

	(
		set -e
		run_test
	)
	# shellcheck disable=SC2181
	if [ $? = 0 ]; then
		echo "Passed"
	else
		echo "Failed"
		return 1
	fi
}
